run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - goimports
    - misspell
    - revive

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
