// Package rtsp implements the RTSP protocol planner.
//
// RTSP (Real Time Streaming Protocol, RFC 2326) is a session-level
// control protocol: a single TCP connection on port 554 carries a
// sequence of control messages (DESCRIBE → 200 OK → SETUP → 200 OK →
// PLAY → 200 OK → TEARDOWN → 200 OK); media data flows over a separate
// UDP sub-flow as RTP (RFC 3550). The planner emits:
//
//  1. TCP 3-way handshake (SYN, SYN-ACK, ACK) with MSS/WScale/SACK options.
//  2. Each RTSPMessage in Dialog as a PSH-ACK payload. Messages longer
//     than MSS are segmented; each segment advances the sender's sequence
//     number. Mandatory RTSP headers (CSeq, Session after the first
//     SETUP response, SETUP Transport, Content-Length) are auto-completed
//     when the user omits them — see completeRTSPHeaders.
//  3. (Optional) RTP media sub-flow: when RTSPConfig.Media is set AND a
//     message has EmitMedia=true, the planner emits N RTP frames as UDP
//     sub-flow packets. The sub-flow shares the parent's GroupID so it
//     routes to the same PacketWorker — wire order = emit order, so RTP
//     frames land right after the PLAY response, where real media
//     appears. For byte-fidelity with real servers, set EmitMedia on the
//     PLAY response: the auto-generated RTP-Info header then carries the
//     exact seq/ssrc/rtptime of the frames that follow.
//  4. TCP 4-way teardown (FIN-ACK, ACK, FIN-ACK, ACK).
//
// All signaling packets share the same 4-tuple (one flow). The sequence
// space is continuous per direction — the next message ACKs all prior
// bytes.
//
// Each RTSPMessage is rendered as text per RFC 2326 §10:
//
//	request-line (or status-line) CRLF
//	header1 CRLF
//	header2 CRLF
//	...
//	CRLF
//	body
//
// Direction "up" = client→server (request), "down" = server→client
// (response). When the user leaves Direction empty, the planner infers
// it: Method set → up request (REDIRECT/PLAY_NOTIFY → down, they are
// server-initiated), StatusCode set → down response.
//
// Header completion (user > auto > none, RFC 2326 §12): CSeq is
// mandatory in every message and auto-assigned incrementing (responses
// echo the request they answer, §12.17). Session is generated by the
// server in the first SETUP response and echoed by every later request
// (§12.37). SETUP Transport is derived from the Media ports (§12.39).
// Content-Length (and Content-Type: application/sdp for responses with
// a body) is auto-appended. The user's own headers always win.
package rtsp

import (
	"context"
	"fmt"
	"math/rand"
	"net"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/trafficgen/trafficgen/internal/core"
)

const (
	DefaultTTL = 64
	// DefaultMSS mirrors internal/protocol/tcp.DefaultMSS and
	// internal/protocol/sip.DefaultMSS (1460). Duplicated here to avoid
	// an import cycle. RFC 879 floor is 536.
	DefaultMSS = 1460

	// MinMSS per RFC 879 (IP+TCP header 20+20+536 = 576-byte minimum
	// packet). Smaller values produce malformed SYNs.
	MinMSS = 536

	// DefaultRTPPort is the fallback RTP port when RTSPMedia leaves
	// SrcPort/DstPort at 0 (the standard RTP port for audio).
	DefaultRTPPort = 5004
)

// Planner implements the RTSP protocol planner.
type Planner struct{}

// NewPlanner creates a new RTSP planner.
func NewPlanner() *Planner { return &Planner{} }

// Name returns the protocol name.
func (p *Planner) Name() string { return "rtsp" }

// Validate validates an RTSP flow spec.
func (p *Planner) Validate(spec core.FlowSpec) error {
	if spec.SrcIP != "" {
		if net.ParseIP(spec.SrcIP) == nil {
			return fmt.Errorf("invalid source IP: %s", spec.SrcIP)
		}
	}
	if spec.DstIP != "" {
		if net.ParseIP(spec.DstIP) == nil {
			return fmt.Errorf("invalid destination IP: %s", spec.DstIP)
		}
	}
	// MSS is a TCP transport parameter; it lives on TCPConfig (spec.TCP.MSS).
	if spec.TCP != nil && spec.TCP.MSS > 0 {
		if spec.TCP.MSS < MinMSS {
			return fmt.Errorf("MSS %d too small (min %d per RFC 879)", spec.TCP.MSS, MinMSS)
		}
	}
	// RTSP without a Dialog produces only a TCP handshake/teardown with no
	// RTSP messages — almost certainly a user error. Reject it explicitly so
	// the caller gets a clear message instead of an empty-looking pcap.
	if spec.RTSP == nil || len(spec.RTSP.Dialog) == 0 {
		return fmt.Errorf("rtsp: dialog is required (config.rtsp.dialog must contain at least one message)")
	}
	return nil
}

// Plan generates packet configs for an RTSP flow.
func (p *Planner) Plan(ctx context.Context, spec core.FlowSpec) (<-chan core.PacketConfig, error) {
	if err := p.Validate(spec); err != nil {
		return nil, err
	}

	configChan := make(chan core.PacketConfig, 256)

	go func() {
		defer close(configChan)

		flowID := fmt.Sprintf("%s-%s-%d-%d", spec.SrcIP, spec.DstIP, spec.SrcPort, spec.DstPort)

		rtspConfig := spec.RTSP
		if rtspConfig == nil {
			rtspConfig = &core.RTSPConfig{}
		}

		effectiveTTL := spec.TTL
		if effectiveTTL == 0 {
			effectiveTTL = DefaultTTL
		}

		mss := uint16(DefaultMSS)
		if spec.TCP != nil && spec.TCP.MSS > 0 {
			mss = spec.TCP.MSS
		}
		synOpts := synOptions(mss)

		now := time.Now()
		packetIndex := uint64(0)
		ipID := uint16(rand.Uint32())
		nextIPID := func() uint16 {
			id := ipID
			ipID++
			return id
		}

		// Random ISN per RFC 6528. User can override client ISN via
		// spec.TCP.InitialSeq for reproducible tests.
		clientSeq := uint32(0)
		if spec.TCP != nil {
			clientSeq = spec.TCP.InitialSeq
		}
		if clientSeq == 0 {
			clientSeq = rand.Uint32()
		}
		serverSeq := rand.Uint32()

		winSize := uint16(65535)

		// --- TCP handshake (SYN, SYN-ACK, ACK) ---
		emit := func(direction, srcMAC, dstMAC, srcIP, dstIP string, srcPort, dstPort uint16, seq, ack uint32, flags uint8, payload []byte) {
			l3 := core.L3Base(srcIP, dstIP, 6, effectiveTTL, nextIPID(), spec)
			l4 := core.L4Config{
				Protocol:   "tcp",
				SrcPort:    srcPort,
				DstPort:    dstPort,
				Seq:        seq,
				Ack:        ack,
				Flags:      flags,
				WindowSize: winSize,
			}
			if flags == 0x02 || flags == 0x12 {
				// SYN or SYN-ACK carries TCP options.
				l4.TCPOptions = synOpts
			}
			cfg := core.PacketConfig{
				FlowID:      flowID,
				PacketIndex: packetIndex,
				Direction:   direction,
				Timestamp:   now,
				L2: core.L2Config{
					SrcMAC:    srcMAC,
					DstMAC:    dstMAC,
					EtherType: core.EtherTypeFor(spec.SrcIP),
				},
				L3:      l3,
				L4:      l4,
				Payload: payload,
			}
			configChan <- cfg
			packetIndex++
		}

		// SYN (client -> server)
		emit("up", spec.SrcMAC, spec.DstMAC, spec.SrcIP, spec.DstIP, spec.SrcPort, spec.DstPort, clientSeq, 0, 0x02, nil)
		clientSeq++
		// SYN-ACK (server -> client)
		emit("down", spec.DstMAC, spec.SrcMAC, spec.DstIP, spec.SrcIP, spec.DstPort, spec.SrcPort, serverSeq, clientSeq, 0x12, nil)
		serverSeq++
		// ACK (client -> server)
		emit("up", spec.SrcMAC, spec.DstMAC, spec.SrcIP, spec.DstIP, spec.SrcPort, spec.DstPort, clientSeq, serverSeq, 0x10, nil)

		// emitData segments payload by MSS and emits each chunk as a
		// PSH-ACK in the given direction, advancing the sender's seq.
		emitData := func(direction, srcMAC, dstMAC, srcIP, dstIP string, srcPort, dstPort uint16, senderSeq, peerSeq uint32, payload []byte) (newSenderSeq uint32) {
			for _, seg := range segmentByMSS(payload, int(mss)) {
				emit(direction, srcMAC, dstMAC, srcIP, dstIP, srcPort, dstPort, senderSeq, peerSeq, 0x18, seg)
				senderSeq += uint32(len(seg))
			}
			return senderSeq
		}

		// --- RTSP dialog (each message becomes one or more PSH-ACK segments) ---
		var dc dialogCtx
		// RTP stream parameters are pre-generated so the auto RTP-Info
		// header in the PLAY response can carry the exact seq/ssrc/rtptime
		// of the frames emitted after it (reference pcap: RTP-Info seq
		// equals the first RTP packet's seq).
		params := &rtpParams{
			ssrc: rand.Uint32(),
			seq:  uint16(rand.Uint32()),
			ts:   rand.Uint32(),
		}
		for _, msg := range rtspConfig.Dialog {
			completeRTSPHeaders(&msg, &dc, spec, rtspConfig.Media, params)
			payload := renderRTSPMessage(msg)
			if len(payload) == 0 {
				continue
			}
			direction := msg.Direction
			if direction == "" {
				direction = inferDirection(msg)
			}
			if direction != "up" && direction != "down" {
				continue
			}
			if direction == "up" {
				clientSeq = emitData("up", spec.SrcMAC, spec.DstMAC, spec.SrcIP, spec.DstIP, spec.SrcPort, spec.DstPort, clientSeq, serverSeq, payload)
			} else {
				serverSeq = emitData("down", spec.DstMAC, spec.SrcMAC, spec.DstIP, spec.SrcIP, spec.DstPort, spec.SrcPort, serverSeq, clientSeq, payload)
			}

			// Emit RTP media sub-flow after this message when the user
			// flagged it. The sub-flow is a UDP flow (separate 4-tuple)
			// but shares the parent's GroupID so it routes to the same
			// PacketWorker — wire order = emit order, so RTP frames land
			// right after this message (typically the PLAY response) and
			// before the next (usually TEARDOWN), matching the reference
			// pcaps. params advances so a later PLAY's RTP-Info describes
			// the continued stream.
			if msg.EmitMedia && rtspConfig.Media != nil {
				emitRTSPMedia(ctx, configChan, rtspConfig.Media, spec, flowID, now, &packetIndex, nextIPID, params)
				dc.mediaEmitted = true
			}
		}

		// --- TCP teardown (FIN-ACK, ACK, FIN-ACK, ACK) ---
		// Client FIN
		emit("up", spec.SrcMAC, spec.DstMAC, spec.SrcIP, spec.DstIP, spec.SrcPort, spec.DstPort, clientSeq, serverSeq, 0x11, nil)
		clientSeq++
		// Server ACK
		emit("down", spec.DstMAC, spec.SrcMAC, spec.DstIP, spec.SrcIP, spec.DstPort, spec.SrcPort, serverSeq, clientSeq, 0x10, nil)
		// Server FIN
		emit("down", spec.DstMAC, spec.SrcMAC, spec.DstIP, spec.SrcIP, spec.DstPort, spec.SrcPort, serverSeq, clientSeq, 0x11, nil)
		serverSeq++
		// Client ACK
		emit("up", spec.SrcMAC, spec.DstMAC, spec.SrcIP, spec.DstIP, spec.SrcPort, spec.DstPort, clientSeq, serverSeq, 0x10, nil)
	}()

	return configChan, nil
}

// renderRTSPMessage converts an RTSPMessage into the RFC 2326 §10 wire
// format:
//
//	request-line or status-line CRLF
//	each header CRLF
//	CRLF (empty line separating headers from body)
//	body (if any)
//
// Content-Length is auto-appended when Body is non-empty AND the user did
// not supply one (matched case-insensitively on the header name). This
// matches real RTSP server behavior: a response with an SDP body always
// carries Content-Length so the client knows where the next message
// starts (important for TCP transport where multiple RTSP messages share
// a connection). The body itself is written verbatim (each SDP line is
// CRLF-terminated per RFC 4566 — the user supplies the CRLFs).
func renderRTSPMessage(msg core.RTSPMessage) []byte {
	var b strings.Builder
	if msg.Method != "" {
		// Request-Line: Method SP Request-URI SP RTSP-Version CRLF
		b.WriteString(msg.Method)
		b.WriteByte(' ')
		b.WriteString(msg.URI)
		b.WriteString(" RTSP/1.0\r\n")
	} else if msg.StatusCode != 0 {
		// Status-Line: RTSP-Version SP Status-Code SP Reason-Phrase CRLF.
		// The reason phrase defaults to the RFC 2326 §10.2 standard phrase
		// for the code; a user StatusText wins (testcase 1.2.24).
		reason := msg.StatusText
		if reason == "" {
			reason = rtspReasonPhrase(msg.StatusCode)
		}
		b.WriteString("RTSP/1.0 ")
		b.WriteString(strconv.Itoa(msg.StatusCode))
		b.WriteByte(' ')
		b.WriteString(reason)
		b.WriteString("\r\n")
	} else {
		// Neither Method nor StatusCode — nothing to emit.
		return nil
	}

	// Headers. Track whether the user supplied Content-Length so we can
	// auto-append one when Body is non-empty and none was provided.
	hasContentLength := false
	for _, h := range msg.Headers {
		b.WriteString(h)
		b.WriteString("\r\n")
		// Header name is everything before the first colon; compare
		// case-insensitively per RFC 2326 §12 (e.g. reference pcap
		// servers write "Content-length:").
		if idx := strings.Index(h, ":"); idx >= 0 {
			name := strings.TrimSpace(h[:idx])
			if strings.EqualFold(name, "Content-Length") {
				hasContentLength = true
			}
		}
	}

	if msg.Body != "" {
		if !hasContentLength {
			b.WriteString(fmt.Sprintf("Content-Length: %d\r\n", len(msg.Body)))
		}
		// Blank line separating headers from body.
		b.WriteString("\r\n")
		b.WriteString(msg.Body)
	} else {
		// No body: still need the blank line to terminate headers.
		b.WriteString("\r\n")
	}

	return []byte(b.String())
}

// dialogCtx tracks the dialog-scoped RTSP state the planner inherits
// into messages that omit it (RFC 2326 §12):
//
//   - CSeq (§12.17) is mandatory in every request and response. Requests
//     get the next number; a response echoes the CSeq of the request it
//     answers (reference pcap: DESCRIBE CSeq:1 → 200 CSeq:1).
//   - Session (§12.37) is issued by the server in the first SETUP
//     response and must be echoed by every later request (SETUP #2,
//     PLAY, PAUSE, TEARDOWN, GET_PARAMETER, ...).
//   - Transport (§12.39) in a SETUP request advertises the client's RTP
//     ports; the SETUP response adds the server's.
//   - RTP-Info (§12.33) in a PLAY response announces the stream's
//     seq/ssrc/rtptime — the same values the emitted RTP frames use.
//
// The user's own headers always win (user > auto > none).
type dialogCtx struct {
	cseq         int    // next CSeq number to assign (auto); 0 = none assigned yet
	lastReqCSeq  string // full CSeq line of the last request (responses echo it)
	lastMethod   string // method of the last request (responses of SETUP/PLAY get Transport/RTP-Info)
	session      string // Session value (generated in the first SETUP response, or user-supplied)
	trackID      string // trackID segment of the last SETUP request URI (RTP-Info url)
	mediaEmitted bool   // an RTP emission happened after the last request (suppresses auto RTP-Info)
}

// completeRTSPHeaders fills the mandatory RTSP headers that a dialog
// message omits, deriving them from the dialog context carried in dc.
// Mutates msg.Headers in place (msg is a per-iteration copy in Plan, so
// the user's RTSPConfig.Dialog is untouched). Messages without both
// Method and StatusCode are left alone — renderRTSPMessage emits nothing
// for them anyway.
func completeRTSPHeaders(msg *core.RTSPMessage, dc *dialogCtx, spec core.FlowSpec, media *core.RTSPMedia, params *rtpParams) {
	isRequest := msg.Method != ""
	isResponse := !isRequest && msg.StatusCode != 0
	if !isRequest && !isResponse {
		return
	}

	if isRequest {
		completeRTSPRequest(msg, dc, spec, media)
	} else {
		completeRTSPResponse(msg, dc, media, params)
	}
}

// completeRTSPRequest fills the mandatory request headers.
//
// CSeq: a request without one gets the next auto number; a user-supplied
// CSeq re-syncs the counter so subsequent fills stay consistent with it
// (RFC 2326 §12.17 — CSeq is a monotonically increasing integer).
//
// URI: a request without one gets "rtsp://<dstIP>/media" (IPv6 hosts
// bracketed per RFC 2326 §12.10 / reference ipv6_rtsp.pcap).
//
// Session: after the server issued one, every request must echo it
// (§12.37 "Session" must be present in all subsequent requests).
//
// Transport: a SETUP request without one gets
// "RTP/AVP;unicast;client_port=<DstPort>-<DstPort+1>" derived from the
// Media ports (§12.39; reference pcap client_port=1024-1025).
//
// Auto-generated headers are prepended as a block in output order (CSeq
// first, matching the reference pcap where CSeq is always the first
// header), so the user's own headers keep their order after them
// (testcase 1.7.5).
func completeRTSPRequest(msg *core.RTSPMessage, dc *dialogCtx, spec core.FlowSpec, media *core.RTSPMedia) {
	// Reset the media-emitted flag: an RTP stream that went out before
	// this request is irrelevant to responses that answer it.
	dc.mediaEmitted = false

	if msg.URI == "" {
		msg.URI = "rtsp://" + rtspHostOf(spec.DstIP) + "/media"
	}

	var auto []string

	// CSeq: user > auto. A user-supplied value re-syncs the counter.
	if v, ok := findHeader(msg.Headers, "CSeq"); ok {
		dc.lastReqCSeq = "CSeq: " + v
		if n := parseCSeqNumber(v); n > 0 {
			dc.cseq = n
		}
	} else {
		dc.cseq++
		line := fmt.Sprintf("CSeq: %d", dc.cseq)
		dc.lastReqCSeq = line
		auto = append(auto, line)
	}

	// Session echo: after the server issued one, every request carries it.
	if dc.session != "" {
		if _, ok := findHeader(msg.Headers, "Session"); !ok {
			auto = append(auto, "Session: "+dc.session)
		}
	}

	// Track the trackID segment of SETUP URIs for the auto RTP-Info url.
	if msg.Method == "SETUP" {
		if id := extractTrackID(msg.URI); id != "" {
			dc.trackID = id
		}
	}

	// Transport: only SETUP requests carry it; only auto-generate when
	// Media config exists (its ports are the negotiated ones).
	if msg.Method == "SETUP" && media != nil {
		if _, ok := findHeader(msg.Headers, "Transport"); !ok {
			dst := media.DstPort
			if dst == 0 {
				dst = DefaultRTPPort
			}
			auto = append(auto, fmt.Sprintf("Transport: RTP/AVP;unicast;client_port=%d-%d", dst, dst+1))
		}
	}

	msg.Headers = append(auto, msg.Headers...)
	dc.lastMethod = msg.Method
}

// completeRTSPResponse fills the mandatory response headers.
//
// CSeq: a response echoes the CSeq of the request it answers (§12.17).
// When the dialog opens with a response (no request seen), it gets the
// next auto number instead.
//
// Session: the server issues it in the first SETUP response (§12.37);
// once issued, every response of the session carries it too (reference
// pcap frames 7/9/11/127 all carry Session).
//
// Transport: a SETUP response echoes the client's transport and appends
// the server's ports (§12.39; reference:
// "client_port=1024-1025;server_port=1024-1025").
//
// Content-Type: a response with a body gets "Content-Type:
// application/sdp" when the user did not supply one (reference pcap
// DESCRIBE 200).
//
// RTP-Info: a PLAY response announces the stream parameters (§12.33).
// Auto-generated only when no media was emitted since the last request —
// i.e. when the stream that follows is still unemitted — with the exact
// params the RTP frames will use. When the user put EmitMedia on the
// PLAY request itself, the stream has already gone out and the response
// gets no auto RTP-Info (the response cannot truthfully describe a
// stream it didn't precede).
func completeRTSPResponse(msg *core.RTSPMessage, dc *dialogCtx, media *core.RTSPMedia, params *rtpParams) {
	var auto []string

	// CSeq: echo the last request's value; a dialog that opens with a
	// response has no request to echo, so it gets the next auto number.
	if _, ok := findHeader(msg.Headers, "CSeq"); !ok {
		if dc.lastReqCSeq != "" {
			auto = append(auto, dc.lastReqCSeq)
		} else {
			dc.cseq++
			auto = append(auto, fmt.Sprintf("CSeq: %d", dc.cseq))
		}
	}

	// Session: issue on the first response of a session; echo it after.
	if v, ok := findHeader(msg.Headers, "Session"); ok {
		if dc.session == "" {
			dc.session = v
		}
	} else if dc.session != "" {
		auto = append(auto, "Session: "+dc.session)
	} else if dc.lastMethod == "SETUP" {
		// The first SETUP response defines the session (reference pcap
		// frame 7: Session: 8d9dea6f8d9deaa8f).
		dc.session = generateSessionID()
		auto = append(auto, "Session: "+dc.session)
	}

	// Transport: the SETUP response echoes the negotiated ports.
	if dc.lastMethod == "SETUP" && media != nil {
		if _, ok := findHeader(msg.Headers, "Transport"); !ok {
			src := media.SrcPort
			if src == 0 {
				src = DefaultRTPPort
			}
			dst := media.DstPort
			if dst == 0 {
				dst = DefaultRTPPort
			}
			auto = append(auto,
				fmt.Sprintf("Transport: RTP/AVP;unicast;client_port=%d-%d;server_port=%d-%d", dst, dst+1, src, src+1))
		}
	}

	// Content-Type: responses with a body are SDP (reference pcap
	// DESCRIBE 200 carries "Content-Type: application/sdp").
	if msg.Body != "" {
		if _, ok := findHeader(msg.Headers, "Content-Type"); !ok {
			auto = append(auto, "Content-Type: application/sdp")
		}
	}

	// RTP-Info: the PLAY response announces the stream about to flow.
	if dc.lastMethod == "PLAY" && media != nil && !dc.mediaEmitted {
		if _, ok := findHeader(msg.Headers, "RTP-Info"); !ok {
			if url := dc.trackID; url != "" {
				// ssrc is printed as a signed int32, the format used by
				// the QuickTime reference pcap ("ssrc=-1919345977" for
				// 0x8D991AC7).
				auto = append(auto, fmt.Sprintf(
					"RTP-Info: url=%s;seq=%d;ssrc=%d;rtptime=%d",
					url, params.seq, int32(params.ssrc), params.ts))
			}
		}
	}

	msg.Headers = append(auto, msg.Headers...)
}

// rtspReasonPhrase maps an RTSP status code to its RFC 2326 §10.2
// standard reason phrase (used when the user leaves StatusText empty).
func rtspReasonPhrase(code int) string {
	switch code {
	case 200:
		return "OK"
	case 201:
		return "Created"
	case 250:
		return "Low on Storage Space"
	case 300:
		return "Multiple Choices"
	case 301:
		return "Moved Permanently"
	case 302:
		return "Moved Temporarily"
	case 303:
		return "See Other"
	case 304:
		return "Not Modified"
	case 305:
		return "Use Proxy"
	case 400:
		return "Bad Request"
	case 401:
		return "Unauthorized"
	case 402:
		return "Payment Required"
	case 403:
		return "Forbidden"
	case 404:
		return "Not Found"
	case 405:
		return "Method Not Allowed"
	case 406:
		return "Not Acceptable"
	case 407:
		return "Proxy Authentication Required"
	case 408:
		return "Request Timeout"
	case 410:
		return "Gone"
	case 411:
		return "Length Required"
	case 412:
		return "Precondition Failed"
	case 413:
		return "Request Entity Too Large"
	case 414:
		return "Request-URI Too Long"
	case 415:
		return "Unsupported Media Type"
	case 451:
		return "Parameter Not Understood"
	case 452:
		return "Conference Not Found"
	case 453:
		return "Not Enough Bandwidth"
	case 454:
		return "Session Not Found"
	case 455:
		return "Method Not Valid in This State"
	case 456:
		return "Header Field Not Valid for Resource"
	case 457:
		return "Invalid Range"
	case 458:
		return "Parameter Is Read-Only"
	case 459:
		return "Aggregate Operation Not Allowed"
	case 460:
		return "Only Aggregate Operation Allowed"
	case 461:
		return "Unsupported Transport"
	case 462:
		return "Destination Unreachable"
	case 463:
		return "Key Management Failure"
	case 500:
		return "Internal Server Error"
	case 501:
		return "Not Implemented"
	case 502:
		return "Bad Gateway"
	case 503:
		return "Service Unavailable"
	case 504:
		return "Gateway Timeout"
	case 505:
		return "RTSP Version Not Supported"
	case 551:
		return "Option not supported"
	case 552:
		return "Session Parameter Not Supported"
	}
	return ""
}

// inferDirection derives the wire direction of a message from its
// Method/StatusCode. Method → up (request); REDIRECT (RFC 2326 §10.6)
// and PLAY_NOTIFY (RFC 7826 §13.4) are server-initiated requests → down.
// StatusCode → down (response). Both empty → "" (message skipped).
func inferDirection(msg core.RTSPMessage) string {
	if msg.Method != "" {
		switch msg.Method {
		case "REDIRECT", "PLAY_NOTIFY":
			return "down"
		}
		return "up"
	}
	if msg.StatusCode != 0 {
		return "down"
	}
	return ""
}

// rtpParams holds the live RTP stream parameters. They start at random
// values (RFC 3550 §5.1) and advance as frames are emitted, so a later
// PLAY response's RTP-Info always describes the next stream.
type rtpParams struct {
	ssrc uint32
	seq  uint16
	ts   uint32
}

// emitRTSPMedia emits the RTP media sub-flow. Each RTP frame is one UDP
// datagram carrying a 12-byte RTP header (RFC 3550 §5.1) + FrameSize
// bytes of payload. Frames flow in the direction given by media.Direction
// (default "down" = server→client, src=spec.DstIP — RTSP servers stream
// media to the client; reference pcap: 192.168.1.27:1024 →
// 192.168.45.2:1024).
//
// Ports: media.SrcPort = server-side send port (server_port), media.
// DstPort = client-side receive port (client_port); 0 = DefaultRTPPort.
// These are the same ports the auto-generated SETUP Transport headers
// advertise, so DPI can associate the RTP stream with the signaling.
//
// Per RFC 3550 §5.1, sequence number and timestamp start at RANDOM
// values. seq increments per packet; timestamp increments by FrameSize
// per packet. The stream advances params in place, so the RTP-Info
// header generated for a later PLAY response describes the next stream.
//
// All RTP frames share the FlowID "{parent}:rtp" so they resequence
// together at the PacketWorker — one RTP stream, one flow.
//
// FileSource: when set, frame payload bytes come from PayloadCache.
// GetOrLoad, split into FrameSize-sized chunks (last chunk may be
// shorter). When set but no cache is injected in the context, the
// function returns WITHOUT emitting — falling through to synthesized
// zero bytes would violate the FileSource > inline precedence contract.
func emitRTSPMedia(
	ctx context.Context,
	configChan chan<- core.PacketConfig,
	media *core.RTSPMedia,
	spec core.FlowSpec,
	parentFlowID string,
	now time.Time,
	packetIndex *uint64,
	nextIPID func() uint16,
	params *rtpParams,
) {
	frames := media.Frames
	if frames <= 0 {
		frames = 1
	}

	var rtpFramePayloads [][]byte
	if media.FileSource != nil {
		pc := core.PayloadCacheFrom(ctx)
		if pc == nil {
			return
		}
		bytes, _ := pc.GetOrLoad(ctx, *media.FileSource)
		rtpFramePayloads = splitRTPFrames(bytes, media.FrameSize)
		frames = len(rtpFramePayloads)
		if frames == 0 {
			frames = 1
		}
	}

	srcPort := media.SrcPort
	if srcPort == 0 {
		srcPort = DefaultRTPPort
	}
	dstPort := media.DstPort
	if dstPort == 0 {
		dstPort = DefaultRTPPort
	}
	pt := media.PayloadType // 0 is a valid PT (PCMU), so no defaulting.
	frameSize := media.FrameSize
	if frameSize == 0 {
		frameSize = 160
	}
	dir := media.Direction
	if dir == "" {
		dir = "down" // RTSP servers stream media to the client.
	}

	// Direction determines L2/L3 tuple. "down" = server→client
	// (spec.DstIP → spec.SrcIP); "up" = reverse. Case-insensitive to
	// match FTP/SIP convention.
	var srcMAC, dstMAC, srcIP, dstIP string
	var srcPortWire, dstPortWire uint16
	if strings.EqualFold(dir, "down") {
		srcMAC, dstMAC = spec.DstMAC, spec.SrcMAC
		srcIP, dstIP = spec.DstIP, spec.SrcIP
		srcPortWire, dstPortWire = srcPort, dstPort
	} else {
		srcMAC, dstMAC = spec.SrcMAC, spec.DstMAC
		srcIP, dstIP = spec.SrcIP, spec.DstIP
		srcPortWire, dstPortWire = dstPort, srcPort
	}

	rtpFlowID := parentFlowID + ":rtp"

	for i := 0; i < frames; i++ {
		// RTP header (12 bytes, no CSRC or extension):
		//   V=2, P=0, X=0, CC=0 -> byte 0 = 0x80
		//   M=0, PT=pt -> byte 1 = pt & 0x7F
		//   Sequence number (16-bit) -> bytes 2-3
		//   Timestamp (32-bit) -> bytes 4-7
		//   SSRC (32-bit) -> bytes 8-11
		// Media payload follows. When FileSource resolved bytes, the
		// payload is the i-th FrameSize-sized chunk (length may vary).
		// Otherwise, the payload is frameSize bytes of zeros.
		var framePayload []byte
		if media.FileSource != nil {
			if i < len(rtpFramePayloads) {
				framePayload = rtpFramePayloads[i]
			}
		} else {
			framePayload = make([]byte, frameSize)
		}
		udpPayload := make([]byte, 12+len(framePayload))
		udpPayload[0] = 0x80 // V=2
		udpPayload[1] = pt & 0x7F
		udpPayload[2] = byte(params.seq >> 8)
		udpPayload[3] = byte(params.seq)
		udpPayload[4] = byte(params.ts >> 24)
		udpPayload[5] = byte(params.ts >> 16)
		udpPayload[6] = byte(params.ts >> 8)
		udpPayload[7] = byte(params.ts)
		udpPayload[8] = byte(params.ssrc >> 24)
		udpPayload[9] = byte(params.ssrc >> 16)
		udpPayload[10] = byte(params.ssrc >> 8)
		udpPayload[11] = byte(params.ssrc)
		copy(udpPayload[12:], framePayload)

		cfg := core.PacketConfig{
			FlowID:      rtpFlowID,
			PacketIndex: *packetIndex,
			Direction:   dir,
			Timestamp:   now,
			L2: core.L2Config{
				SrcMAC:    srcMAC,
				DstMAC:    dstMAC,
				EtherType: core.EtherTypeFor(srcIP),
			},
			L3:      core.L3Base(srcIP, dstIP, 17, effectiveTTLOf(spec), nextIPID(), spec),
			L4:      core.L4Config{Protocol: "udp", SrcPort: srcPortWire, DstPort: dstPortWire},
			Payload: udpPayload,
		}
		configChan <- cfg
		*packetIndex++
		params.seq++
		params.ts += uint32(frameSize)
	}
}

// findHeader returns the value of the first header whose name matches
// (case-insensitive per RFC 2326 §12 — header names are not
// case-sensitive), and whether one was found.
func findHeader(headers []string, name string) (string, bool) {
	for _, h := range headers {
		if idx := strings.Index(h, ":"); idx >= 0 {
			if strings.EqualFold(strings.TrimSpace(h[:idx]), name) {
				return strings.TrimSpace(h[idx+1:]), true
			}
		}
	}
	return "", false
}

// parseCSeqNumber extracts the integer from a CSeq header value
// ("10" from "10"). Returns -1 when the value is not a number — the
// caller then leaves the auto counter untouched.
func parseCSeqNumber(v string) int {
	v = strings.TrimSpace(v)
	if v == "" {
		return -1
	}
	for _, c := range v {
		if c < '0' || c > '9' {
			return -1
		}
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		return -1
	}
	return n
}

// generateSessionID returns a 15-digit lowercase hex session ID, the
// format used by the QuickTime Streaming Server reference pcap
// ("8d9dea6f8d9deaa8f").
func generateSessionID() string {
	const hex = "0123456789abcdef"
	b := make([]byte, 15)
	for i := range b {
		b[i] = hex[rand.Intn(16)]
	}
	return string(b)
}

// rtspHostOf formats an IP as an RTSP URL host: IPv6 addresses are
// bracketed per RFC 2326 §12.10 (reference ipv6_rtsp.pcap:
// "rtsp://[3FFE:0:0:0:200:FF:FE00:4]/35k_1sec.mov").
func rtspHostOf(ip string) string {
	if strings.Contains(ip, ":") {
		return "[" + ip + "]"
	}
	return ip
}

// trackIDRe matches a "trackID=..." segment in a SETUP request URI
// (reference: "rtsp://host/media/trackID=5" → "trackID=5").
var trackIDRe = regexp.MustCompile(`(?i)trackID=([^/?#]+)`)

// extractTrackID returns the "trackID=N" segment of an RTSP URI, or the
// last path segment when no trackID is present. Empty when the URI has
// no path segments.
func extractTrackID(uri string) string {
	if m := trackIDRe.FindString(uri); m != "" {
		return m
	}
	seg := uri
	if idx := strings.LastIndex(uri, "/"); idx >= 0 {
		seg = uri[idx+1:]
	}
	return seg
}

// segmentByMSS splits a payload into MSS-sized chunks (RFC 879). An
// empty payload yields a single empty chunk (a bare PSH-ACK). Mirrors
// internal/protocol/sip.segmentByMSS.
func segmentByMSS(payload []byte, mss int) [][]byte {
	if mss <= 0 {
		return [][]byte{payload}
	}
	if len(payload) == 0 {
		return [][]byte{{}}
	}
	chunks := make([][]byte, 0, (len(payload)+mss-1)/mss)
	for len(payload) > 0 {
		n := len(payload)
		if n > mss {
			n = mss
		}
		chunks = append(chunks, payload[:n])
		payload = payload[n:]
	}
	return chunks
}

// synOptions builds TCP options for SYN packets: MSS, Window Scale, and
// SACK-Permitted. Mirrors internal/protocol/sip.synOptions — duplicated
// to avoid an import cycle.
func synOptions(mss uint16) []core.TCPOption {
	if mss == 0 {
		mss = DefaultMSS
	}
	opts := make([]core.TCPOption, 0, 3)
	opts = append(opts, core.TCPOption{Kind: core.TCPOptMSS, Data: []byte{byte(mss >> 8), byte(mss)}})
	opts = append(opts, core.TCPOption{Kind: core.TCPOptWinScale, Data: []byte{0x07}})
	opts = append(opts, core.TCPOption{Kind: core.TCPOptSACKPermit})
	return opts
}

// effectiveTTLOf returns the flow's TTL, defaulting to DefaultTTL when
// unset. Mirrors internal/protocol/sip.effectiveTTLOf.
func effectiveTTLOf(spec core.FlowSpec) uint8 {
	if spec.TTL != 0 {
		return spec.TTL
	}
	return DefaultTTL
}

// splitRTPFrames splits media bytes into FrameSize-sized chunks (the
// last chunk may be smaller). FrameSize <= 0 puts the whole bytes on a
// single frame. Mirrors internal/protocol/sip.splitRTPFrames.
func splitRTPFrames(b []byte, frameSize int) [][]byte {
	if len(b) == 0 {
		return nil
	}
	if frameSize <= 0 {
		return [][]byte{b}
	}
	frames := make([][]byte, 0, (len(b)+frameSize-1)/frameSize)
	for len(b) > 0 {
		n := len(b)
		if n > frameSize {
			n = frameSize
		}
		frames = append(frames, b[:n])
		b = b[n:]
	}
	return frames
}
